eosnetworkfoundation/eos-system-contracts

README.md
Clarified where the user wants to be when they're trying to build the contracts repo.
=> clarify location

.github/workflows/ubuntu-2004.yml, CMakeLists.txt, README.md, contracts/eosio.system/CMakeLists.txt, contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/src/eosio.system.cpp, tests/eosio.system_tests.cpp
=> Add configuration actions for new protocol features

contracts/eosio.system/src/delegate_bandwidth.cpp, contracts/eosio.system/src/voting.cpp, tests/eosio.system_tests.cpp
Equivalent to the original patch
=> Reapply b1 patches

contracts/CMakeLists.txt, contracts/eosio.boot/CMakeLists.txt, contracts/eosio.boot/include/eosio.boot/eosio.boot.hpp, contracts/eosio.boot/ricardian/eosio.boot.contracts.md.in, contracts/eosio.boot/src/eosio.boot.cpp
This is required for the changes in the tutorial for this PR: https://github.com/eosnetworkfoundation/mandel/pull/309
=> Add Boot Contract

CMakeLists.txt, contracts/CMakeLists.txt
Update CDT dependency to CDT 3.0.
=> Update CDT dependency to CDT 3.0

contracts/eosio.system/src/eosio.system.cpp
Increase the maximum call depth for `wasmcfg` from 251 to 1024.
=> up max_call_depth to 1024

CMakeLists.txt
=> Bump version to 3.2.0-dev

contracts/eosio.system/ricardian/eosio.system.clauses.md, contracts/eosio.system/ricardian/eosio.system.contracts.md.in
=> [3.1 -> main] Update ricardian contracts

README.md
Brings #40 to `main`. Resolves #23.
=> [3.1 -> main] Update readme and version bump to 3.1.0

contracts/CMakeLists.txt
Merge https://github.com/eosnetworkfoundation/eos-system-contracts/pull/43 from release/3.1 o main
=> [3.1 -> main] Update ICON_BASE_URL to a working address

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/src/rex.cpp
Resolve https://github.com/eosnetworkfoundation/eos-system-contracts/issues/45
Port from https://github.com/AntelopeIO/reference-contracts/pull/4
=> [3.1] Replace usage of deque and map with vector in system contracts

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/src/rex.cpp
Resolve https://github.com/eosnetworkfoundation/eos-system-contracts/issues/45
Merge from https://github.com/eosnetworkfoundation/eos-system-contracts/pull/46
=> [3.1 -> main] Replace usage of deque and map with vector in system contracts

CMakeLists.txt
=> [3.1] bump version to 3.1.1

docs/01_key-concepts/03_cpu.md, docs/01_key-concepts/04_net.md
Resolves eosnetworkfoundation/devrel#193
=> [3.1] Remove eos.io references from docs portal

.cspell/eos-system-contracts-custom-dictionary.txt, contracts/CMakeLists.txt, contracts/eosio.fees/CMakeLists.txt, contracts/eosio.fees/include/eosio.fees/eosio.fees.hpp, contracts/eosio.fees/src/eosio.fees.cpp, contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/ricardian/eosio.system.contracts.md.in, contracts/eosio.system/src/delegate_bandwidth.cpp, contracts/eosio.system/src/eosio.system.cpp, contracts/eosio.system/src/powerup.cpp, contracts/eosio.system/src/producer_pay.cpp, contracts/eosio.system/src/rex.cpp, contracts/eosio.token/include/eosio.token/eosio.token.hpp, contracts/eosio.token/ricardian/eosio.token.contracts.md.in, contracts/eosio.token/src/eosio.token.cpp, tests/contracts.hpp.in, tests/eosio.fees_tests.cpp, tests/eosio.msig_tests.cpp, tests/eosio.powerup_tests.cpp, tests/eosio.system_ram_tests.cpp, tests/eosio.system_schedules_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp, tests/eosio.token_tests.cpp
This PR merges in the [tokenomics](https://github.com/AntelopeIO/reference-contracts/tree/tokenomics) changes from the reference contracts defined in these PRs: 
- https://github.com/AntelopeIO/reference-contracts/pull/81
- https://github.com/AntelopeIO/reference-contracts/pull/79
- https://github.com/AntelopeIO/reference-contracts/pull/78
- https://github.com/eosnetworkfoundation/eosio.fees
=> Tokenomics Changes

tests/eosio.system_rex_matured_tests.cpp
Add a test for zero day, instant, rex maturity. This fails do to a check in the code.
=> validate zero day maturity fails

CMakeLists.txt
=> Change version to 3.6-dev

README.md
Updates readme with clarity on required spring release
Maintains main version
=> Merge official 3.6 release

.github/workflows/build.yaml, contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/src/delegate_bandwidth.cpp, contracts/eosio.system/src/eosio.system.cpp, contracts/eosio.token/include/eosio.token/eosio.token.hpp, tests/contracts.hpp.in, tests/eosio.powerup_tests.cpp, tests/eosio.system_blockinfo_tests.cpp, tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp
Resolves #166.
See [requirements](https://hackmd.io/2b33DI3cQMa0NBFbqGapiQ?view) and technical [proposal](https://hackmd.io/re3HaZiZQnWNBqYTEvRxVA?view).
=> Add support for gifting RAM, which is encumbered and cannot be sold or transfered.

CMakeLists.txt
Bump version to v3.6.1 for update of ricardian clauses
=> bump version to 3.6.1 in release branch

contracts/eosio.system/src/eosio.system.cpp, tests/eosio.system_tests.cpp
This fixes many compilation warnings with current clang, and also improves some error messages from `newaccount`.
=> Fix warnings and improve error messages
