.github/workflows/ubuntu-2004.yml, tests/CMakeLists.txt, tests/eosio.limitauth_tests.cpp, tests/eosio.msig_tests.cpp, tests/eosio.powerup_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp, tests/eosio.token_tests.cpp, tests/eosio.wrap_tests.cpp
The tests now build and pass with the latest Mandel (tested manually). However, the latest container produced by Mandel's cicd triggers a cicd-only issue in this repo, so this PR doesn't update to it. `eosio-ld` on the newest container, when used by this cicd, times out at 6 hours. The same procedure run locally using the newest container succeeds. `nproc` on the cicd system is `2`.
=> Fix tests to be compatable with Mandel

contracts/eosio.system/ricardian/eosio.system.clauses.md, contracts/eosio.system/ricardian/eosio.system.contracts.md.in
=> Updated ricardians

contracts/CMakeLists.txt
Resolve https://github.com/eosnetworkfoundation/eos-system-contracts/issues/42
Change CON_BASE_URL to a working address https://raw.githubusercontent.com/eosnetworkfoundation/eos-system-contracts/main/contracts/icons (it was http://127.0.0.1/ricardian_assets/eosio.contracts/icons)
=> [3.1] Change ICON_BASE_URL to a working address

.github/workflows/build.yaml, CMakeLists.txt, tests/CMakeLists.txt
There is a version check that Leap's eosiotester is an expected compatible version and nominally it is useful and helpful, but it makes testing contracts with `main` of `leap` difficult even when it's expected to work. The check will balk that Leap is `4.0.0` while contracts is looking for `3.x` even though we haven't made any incompatible changes.
Change this check to be clutched in based on an `option()`, and enable the option by default (so no functional change by default).
And then disable the check in CI so that it's easier to spot check any version combination. This is maybe a little more contentious (maybe we won't notice we need to change eos-system-contracts before releasing Leap 4.0.0), so I'm curious for opinions on if it should be configurable instead.
=> add a cmake option to skip the leap version check, and skip in CI

tests/eosio.token_tests.cpp
Noticed these minor outdated quirks while porting the token tests to a new token.
=> some very minor eosio.token test cleanups

tests/eosio.limitauth_tests.cpp, tests/eosio.msig_tests.cpp, tests/eosio.system_tests.cpp, tests/eosio.token_tests.cpp, tests/eosio.wrap_tests.cpp, tests/main.cpp
This header file is unused and now removed in Leap's main `branch`
=> remove `Runtime.h` include that no longer exists in Leap's libtester

tests/eosio.powerup_tests.cpp
whoops, somehow I managed to miss one of these `Runtime.h` in #67
=> remove `Runtime.h` include that no longer exists in Leap's libtester, again

.github/workflows/build.yaml, CMakeLists.txt, contracts/CMakeLists.txt, tests/CMakeLists.txt
Backport:
- add cmake option to enable/disable Leap eosiotester version check.
- set SYSTEM_ENABLE_LEAP_VERSION_CHECK off in CI
Added:
- add cmake option to enable/disable cdt version check.
- set SYSTEM_ENABLE_CDT_VERSION_CHECK off in CI
=> [3.1] Disable version check opts for leap and cdt

.github/workflows/build.yaml, CMakeLists.txt, contracts/CMakeLists.txt
merging forward https://github.com/eosnetworkfoundation/eos-system-contracts/pull/79 into `main`
Adding option to disable version checks to make it easier to leverage the contracts in mixed version test scenarios.
Added:
- add cmake option to enable/disable cdt version check.
- set SYSTEM_ENABLE_CDT_VERSION_CHECK off in CI
=> [3.1 -> main] Disable version check opts for leap and cdt

tests/eosio.limitauth_tests.cpp, tests/eosio.msig_tests.cpp, tests/eosio.powerup_tests.cpp, tests/eosio.system_tests.cpp, tests/eosio.token_tests.cpp, tests/eosio.wrap_tests.cpp, tests/main.cpp
Backport: This header file is unused and now removed in Leap's main branch
This is to make it easier to leverage the contracts in mixed version test scenarios.
See PRs where this was done into `main`: https://github.com/eosnetworkfoundation/eos-system-contracts/pull/67 and https://github.com/eosnetworkfoundation/eos-system-contracts/pull/68
=> [3.1] remove Runtime.h include that no longer exists in Leap's libtester

tests/eosio.powerup_tests.cpp
Backports Fix for explicit time_point_sec conversion without the bump to the version.
reference: https://github.com/eosnetworkfoundation/eos-system-contracts/pull/75 and commit: 97d3faab7ee6995dd2d310e94e3f3dcb368ea602
=> [3.1] Fix for explicit time_point_sec conversion

tests/CMakeLists.txt
Allow system contracts to build against Leap 5. Targeted to release/3.2 branch
=> [3.2] Bump Leap v5 

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/ricardian/eosio.system.contracts.md.in, contracts/eosio.system/src/delegate_bandwidth.cpp, tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
New RAM system contract action to transfer RAM from one account to another without any fees.
- `from` must have sufficient `ram_bytes` prior to transfer
- `from` decrease `ram_bytes` by `bytes`
- `to` must exists
- `to` account can be a contract
- `to` account can have zero available RAM bytes
- `to` increase `ram_bytes` by `bytes`
- handle `ram_managed` accounts
- `from {name}`
- `to {name}`
- `bytes {int64}`
- `memo {string}` (via https://github.com/eosnetworkfoundation/eos-system-contracts/pull/104)
```c++
/**
* Logging for ram changes
*
* @param owner - the ram owner account,
* @param bytes - the bytes balance change,
* @param ram_bytes - the ram bytes held by owner after the action.
*/
[[eosio::action]]
void logramchange( const name& owner, int64_t bytes, int64_t ram_bytes );
```
- …
=> Transferable RAM

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/ricardian/eosio.system.contracts.md.in, contracts/eosio.system/src/delegate_bandwidth.cpp, tests/CMakeLists.txt, tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp
New RAM system contract action to transfer RAM from one account to another without any fees.
- Charges 0% fee to transfer
- Only uncommited RAM can be transferred
- Notify `to` & `from` using `require_recipient`
- Memo cannot exceed 256 bytes
- returns struct `action_return_ramtransfer`
New RAM system contract action to burn RAM from owner account.
- Burned RAM is transferred to `eosio.null` account
- Should have no impact on RAM Bancor market, RAM supply should remain unchanged
- returns struct `action_return_ramtransfer`
Add buy RAM logging by including additional inline actions and notifications via the use of `require_recipient`.
`bytes` & `quant` are computed values based on Bancor algorithm market.
This allows `payer` or `receiver` to confirm exact bytes sent/received via …
=> New ram_actions to transfer ram between accounts

.cicd/defaults.json, .github/workflows/build.yaml
Currently set to use Leap v3, need to update CICD to Leap v5. Fixes #139
=> Update CICD build to use Leap v5

tests/eosio.system_ram_tests.cpp, tests/eosio.system_tester.hpp
Add a test to validate the action return from `buyramburn`
=> Test buyramburn return values

contracts/eosio.bpay/src/eosio.bpay.cpp
A small fix for a low-threat problem identified in the audit.
=> Use actual producer list to split rewards instead of configured max

README.md, docs/01_key-concepts/02_system_resources.md, docs/01_key-concepts/03_cpu.md, docs/01_key-concepts/04_net.md, docs/01_key-concepts/05_ram.md, docs/04_guides/05_how-to-create-issue-and-transfer-a-token.md
Update README build instructions to reference spring, and update required CDT version to 4.1
=> [3.6] Update README to Spring

contracts/eosio.system/src/eosio.system.cpp
Avoid unnecessary changes and database updates when the rate of RAM issuance per block is 0.
Resolves #165 .
=> Avoid database update when new ram is not issued with every block.

contracts/eosio.system/ricardian/eosio.system.clauses.md
This occurred when instant finality functionality was pulled from reference-contracts into eos-system-contracts. This commit restores the clauses.
This reverts commit ed0f23d7b01da9e48ff9feb04d2c50730304d45e.
Restores Ricardian clauses for system actions.
No API Changes
No Documentation Updates
=> [3.6] Restore ricardian clauses which were accidently removed

contracts/eosio.system/ricardian/eosio.system.clauses.md
This occurred when instant finality functionality was pulled from reference-contracts into eos-system-contracts. This commit restores the clauses. Main merge of [PR# 177](https://github.com/eosnetworkfoundation/eos-system-contracts/pull/177)
This reverts commit ed0f23d7b01da9e48ff9feb04d2c50730304d45e.
Restores Ricardian clauses for system actions.
No API Changes
No Documentation Updates
=> [3.6 -> main] restore ricardian clauses

contracts/eosio.system/include/eosio.system/canon_name.hpp, contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/src/eosio.system.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
Resolves #186
Note: the `struct canon_name_t` implements the checks of whether a `name` is a subset of another `name`. For performance reasons, this is implemented by shifting,  masking and comparing the `uint64_t` value. 
Probably the equivalent implementation below using strings is easier to understand (but less efficient), which is why I used the `uint64_t` version, but this could be changed if needed.
```
struct canon_name_t {
std::string _pattern;
canon_name_t(name n) : _pattern(n.to_string()) {}
size_t size() const { return _pattern.size(); }
bool is_suffix_of(const canon_name_t& target) const {
assert(size() < target.size());
size_t diff = target.size() - size();
return strcmp(&_pattern[0], &target._pattern[diff]) == 0 && target._pattern[diff-1] == '.';
}
bool found_in(const …
```
=> Account Name Restriction in System Contract

contracts/eosio.system/include/eosio.system/eosio.system.hpp, contracts/eosio.system/src/eosio.system.cpp, tests/eosio.system_tester.hpp, tests/eosio.system_tests.cpp
=> Add a `hash` / `reveal` mechanism to avoid revealing the reserved account names when activating the blacklist.

contracts/eosio.system/src/eosio.system.cpp, tests/eosio.system_tests.cpp
Allow to provide one (or more) 13 character names in the deny pattern vector, in order to add a salt which makes the actual pattern impossible to guess.
=> Silently ignore 13 character or empty patterns in the deny name vector.
